-- `ENF_R_DATA`

CREATE TABLE IF NOT EXISTS `ENF_R_DATA` (
  `ID` int(11) NOT NULL,
  `LABEL` varchar(255) NOT NULL,
  `TYPE` varchar(255) NOT NULL,
  `SORT_ORDER` int(11) NOT NULL,
  `PARENT_ID` int(11) DEFAULT NULL,
  `CREATED_BY` varchar(255) NOT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `LAST_MODIFIED` varchar(255) DEFAULT NULL,
  `LAST_MODIFIED_DATETIME` datetime DEFAULT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID`)
)

-- `ENF_EA_ITEM_REPOSITORY`

CREATE TABLE IF NOT EXISTS `ENF_EA_ITEM_REPOSITORY` (
  `EA_ITEM_REPOSITORY_ID` int(11) NOT NULL AUTO_INCREMENT,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `BODY_TEXT` varchar(4000) DEFAULT NULL,
  `INTERNAL_NOTE` varchar(4000) DEFAULT NULL,
  `STATUS_ID` int(11) NOT NULL,
  `CREATED_BY` varchar(255) NOT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `LAST_MODIFIED_BY` varchar(255) NOT NULL,
  `LAST_MODIFIED_DATETIME` datetime NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL,
  PRIMARY KEY (`EA_ITEM_REPOSITORY_ID`),
  KEY `FK_enfEAItemRepositoryStatusId` (`STATUS_ID`)
)

ALTER TABLE `ENF_EA_ITEM_REPOSITORY`
  ADD CONSTRAINT `FK_enfEAItemRepositoryStatusId` FOREIGN KEY (`STATUS_ID`) REFERENCES `ENF_R_DATA` (`ID`);
COMMIT;

-- `ENF_ENFORCEMENT_ACTION`

CREATE TABLE IF NOT EXISTS `ENF_ENFORCEMENT_ACTION` (
  `ENFORCEMENT_ACTION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TYPE_ID` int(11) NOT NULL,
  `ISSUER_ID` int(11) NOT NULL,
  `INTERNAL_NOTE` varchar(4000) DEFAULT NULL,
  `STATUS_ID` int(11) NOT NULL,
  `ISSUER_STATUS_ID` int(11) DEFAULT NULL,
  `EVENT_DATE` date NOT NULL,
  `NOTIFIED_DATE` date DEFAULT NULL,
  `ACKNOWLEDGE_DATE` date DEFAULT NULL,
  `ACKNOWLEDGE_BY` varchar(255) DEFAULT NULL,
  `CLOSE_DATE` date DEFAULT NULL,
  `ASSIGNED_ANALYST_USERNAME` varchar(255) NOT NULL,
  `CREATED_BY` varchar(255) NOT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `LAST_MODIFIED_BY` varchar(255) NOT NULL,
  `LAST_MODIFIED_DATETIME` datetime NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL,
  PRIMARY KEY (`ENFORCEMENT_ACTION_ID`),
  KEY `FK_enfEnforcementActionTypeId` (`TYPE_ID`),
  KEY `FK_enfEnforcementActionIssuerId` (`ISSUER_ID`),
  KEY `FK_enfEnforcementActionStatusId` (`STATUS_ID`),
  KEY `FK_enfEnforcementActionIssuerStatusId` (`ISSUER_STATUS_ID`)
)

ALTER TABLE `ENF_ENFORCEMENT_ACTION`
  ADD CONSTRAINT `FK_enfEnforcementActionIssuerId` FOREIGN KEY (`ISSUER_ID`) REFERENCES `OIPM_ISSUER` (`ISSUER_ID`),
  ADD CONSTRAINT `FK_enfEnforcementActionIssuerStatusId` FOREIGN KEY (`ISSUER_STATUS_ID`) REFERENCES `ENF_R_DATA` (`ID`),
  ADD CONSTRAINT `FK_enfEnforcementActionStatusId` FOREIGN KEY (`STATUS_ID`) REFERENCES `ENF_R_DATA` (`ID`),
  ADD CONSTRAINT `FK_enfEnforcementActionTypeId` FOREIGN KEY (`TYPE_ID`) REFERENCES `ENF_R_DATA` (`ID`);
COMMIT;

-- `ENF_REASON`

CREATE TABLE IF NOT EXISTS `ENF_REASON` (
  `REASON_ID` int(11) NOT NULL AUTO_INCREMENT,
  `LABEL` varchar(255) NOT NULL,
  `DEFAULT_DETAIL` varchar(4000) DEFAULT NULL,
  `SORT_ORDER` int(11) DEFAULT NULL,
  `CREATED_BY` varchar(255) NOT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `LAST_MODIFIED_BY` varchar(255) NOT NULL,
  `LAST_MODIFIED_DATETIME` datetime NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL,
  PRIMARY KEY (`REASON_ID`)
)

-- `ENF_INTERACTION`

CREATE TABLE IF NOT EXISTS `ENF_INTERACTION` (
  `INTERACTION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ENFORCEMENT_ACTION_ID` int(11) NOT NULL,
  `SUBJECT` varchar(255) NOT NULL,
  `INTERACTION_FORM_ID` int(11) NOT NULL,
  `OTHER_INTERACTION_FORM` varchar(255) DEFAULT NULL,
  `INTERACTION_DATE` date NOT NULL,
  `ATTENDEES` varchar(2000) NOT NULL,
  `COMMENTS` varchar(4000) NOT NULL,
  `IS_CMP_AMOUNT_DISCLOSED` tinyint(1) NOT NULL,
  `CREATED_BY` varchar(255) NOT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `LAST_MODIFIED_BY` varchar(255) DEFAULT NULL,
  `LAST_MODIFIED_DATETIME` datetime DEFAULT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL,
  PRIMARY KEY (`INTERACTION_ID`),
  KEY `FK_INTERACTION_ENFORCEMENT_ACTION_ID` (`ENFORCEMENT_ACTION_ID`)
)

ALTER TABLE `ENF_INTERACTION`
  ADD CONSTRAINT `FK_INTERACTION_ENFORCEMENT_ACTION_ID` FOREIGN KEY (`ENFORCEMENT_ACTION_ID`) REFERENCES `ENF_ENFORCEMENT_ACTION` (`ENFORCEMENT_ACTION_ID`);
COMMIT;

-- `ENF_EVIDENCE`

CREATE TABLE IF NOT EXISTS `ENF_EVIDENCE` (
  `EVIDENCE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ENFORCEMENT_ACTION_ID` int(11) NOT NULL,
  `NAME` varchar(255) NOT NULL,
  `DETAIL` varchar(4000) DEFAULT NULL,
  `CREATED_BY` varchar(255) NOT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `LAST_MODIFIED` varchar(255) DEFAULT NULL,
  `LAST_MODIFIED_DATETIME` datetime DEFAULT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL,
  PRIMARY KEY (`EVIDENCE_ID`),
  KEY `FK_enfEnforcementActionEnforcementActionId` (`ENFORCEMENT_ACTION_ID`)
)

ALTER TABLE `ENF_EVIDENCE`
  ADD CONSTRAINT `FK_enfEnforcementActionEnforcementActionId` FOREIGN KEY (`ENFORCEMENT_ACTION_ID`) REFERENCES `ENF_ENFORCEMENT_ACTION` (`ENFORCEMENT_ACTION_ID`);
COMMIT;

-- `ENF_ENFORCEMENT_ACTION_ITEM`

CREATE TABLE IF NOT EXISTS `ENF_ENFORCEMENT_ACTION_ITEM` (
  `ENFORCEMENT_ACTION_ITEM_ID` int(11) NOT NULL AUTO_INCREMENT,
  `EA_ITEM_REPOSITORY_ID` int(11) DEFAULT NULL,
  `ENFORCEMENT_ACTION_ID` int(11) NOT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `BODY_TEXT` varchar(4000) DEFAULT NULL,
  `INTERNAL_NOTE` varchar(4000) DEFAULT NULL,
  `STATUS_ID` int(11) NOT NULL,
  `ISSUER_STATUS_ID` int(11) DEFAULT NULL,
  `DUE_DATE` date DEFAULT NULL,
  `SENT_DATE` date DEFAULT NULL,
  `CREATED_BY` varchar(255) NOT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `LAST_MODIFIED_BY` varchar(255) NOT NULL,
  `LAST_MODIFIED_DATETIME` datetime NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL,
  PRIMARY KEY (`ENFORCEMENT_ACTION_ITEM_ID`),
  KEY `FK_enfEnforcementActionItemStatusId` (`STATUS_ID`),
  KEY `FK_enfEnforcementActionItemIssuerStatusId` (`ISSUER_STATUS_ID`),
  KEY `FK_enfEnforcementActionItemEAId` (`ENFORCEMENT_ACTION_ID`),
  KEY `FK_enfEnforcementActionItemEaItemRepoId` (`EA_ITEM_REPOSITORY_ID`)
)

ALTER TABLE `ENF_ENFORCEMENT_ACTION_ITEM`
  ADD CONSTRAINT `FK_enfEnforcementActionItemEAId` FOREIGN KEY (`ENFORCEMENT_ACTION_ID`) REFERENCES `ENF_ENFORCEMENT_ACTION` (`ENFORCEMENT_ACTION_ID`),
  ADD CONSTRAINT `FK_enfEnforcementActionItemEaItemRepoId` FOREIGN KEY (`EA_ITEM_REPOSITORY_ID`) REFERENCES `ENF_EA_ITEM_REPOSITORY` (`EA_ITEM_REPOSITORY_ID`),
  ADD CONSTRAINT `FK_enfEnforcementActionItemIssuerStatusId` FOREIGN KEY (`ISSUER_STATUS_ID`) REFERENCES `ENF_R_DATA` (`ID`),
  ADD CONSTRAINT `FK_enfEnforcementActionItemStatusId` FOREIGN KEY (`STATUS_ID`) REFERENCES `ENF_R_DATA` (`ID`);
COMMIT;

-- ENF_ACTION_REASON_LINK

CREATE TABLE IF NOT EXISTS `ENF_ACTION_REASON_LINK` (
  `LINK_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ENFORCEMENT_ACTION_ID` int(11) NOT NULL,
  `REASON_ID` int(11) NOT NULL,
  `DETAIL` varchar(5000) NOT NULL,
  `CREATED_BY` varchar(255) NOT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `LAST_MODIFIED_BY` varchar(255) NOT NULL,
  `LAST_MODIFIED_DATETIME` datetime NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL,
  PRIMARY KEY (`LINK_ID`),
  KEY `FK_enfActionReasonLinkEnforcementActionId` (`ENFORCEMENT_ACTION_ID`),
  KEY `FK_enfActionReasonLinkReasonId` (`REASON_ID`)
)

ALTER TABLE `ENF_ACTION_REASON_LINK`
  ADD CONSTRAINT `FK_enfActionReasonLinkEnforcementActionId` FOREIGN KEY (`ENFORCEMENT_ACTION_ID`) REFERENCES `ENF_ENFORCEMENT_ACTION` (`ENFORCEMENT_ACTION_ID`),
  ADD CONSTRAINT `FK_enfActionReasonLinkReasonId` FOREIGN KEY (`REASON_ID`) REFERENCES `ENF_REASON` (`REASON_ID`);
COMMIT;

-- `ENF_SETTLEMENT_AGREEMENT`

CREATE TABLE IF NOT EXISTS `ENF_SETTLEMENT_AGREEMENT` (
  `SETTLEMENT_AGREEMENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ENFORCEMENT_ACTION_ID` int(11) NOT NULL,
  `CMP_DOLLAR_AMOUNT` decimal(10,0) DEFAULT NULL,
  `IS_APPROVED` tinyint(1) NOT NULL,
  `SENT_TO_ISSUER_DATE` date DEFAULT NULL,
  `ISSUER_SIGNED_BY` varchar(255) DEFAULT NULL,
  `ISSUER_SIGNED_DATE` date DEFAULT NULL,
  `GNMA_SIGNED_BY` varchar(255) DEFAULT NULL,
  `GNMA_SIGNED_DATE` date DEFAULT NULL,
  `CREATED_BY` varchar(255) NOT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `LAST_MODIFIED_BY` varchar(255) DEFAULT NULL,
  `LAST_MODIFIED_DATETIME` datetime DEFAULT NULL,
  `IS_ACTIVE` int(1) NOT NULL,
  PRIMARY KEY (`SETTLEMENT_AGREEMENT_ID`),
  KEY `FK_ENFORCEMENT_ACTION_ID` (`ENFORCEMENT_ACTION_ID`)
)

ALTER TABLE `ENF_SETTLEMENT_AGREEMENT`
  ADD CONSTRAINT `FK_ENFORCEMENT_ACTION_ID` FOREIGN KEY (`ENFORCEMENT_ACTION_ID`) REFERENCES `ENF_ENFORCEMENT_ACTION` (`ENFORCEMENT_ACTION_ID`);
COMMIT;

-- `ENF_SETTLEMENT_AGREEMENT_DOCUMENT`

CREATE TABLE IF NOT EXISTS `ENF_SETTLEMENT_AGREEMENT_DOCUMENT` (
  `SETTLEMENT_AGREEMENT_DOCUMENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `SETTLEMENT_AGREEMENT_ID` int(11) NOT NULL,
  `DOCUMENT_ID` int(11) NOT NULL,
  `CREATED_BY` varchar(255) NOT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `LAST_MODIFIED_BY` varchar(255) DEFAULT NULL,
  `LAST_MODIFIED_DATETIME` datetime DEFAULT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL,
  PRIMARY KEY (`SETTLEMENT_AGREEMENT_DOCUMENT_ID`),
  KEY `FK_SETTLEMENT_AGREEMENT_ID` (`SETTLEMENT_AGREEMENT_ID`)
)

ALTER TABLE `ENF_SETTLEMENT_AGREEMENT_DOCUMENT`
  ADD CONSTRAINT `FK_SETTLEMENT_AGREEMENT_ID` FOREIGN KEY (`SETTLEMENT_AGREEMENT_ID`) REFERENCES `ENF_SETTLEMENT_AGREEMENT` (`SETTLEMENT_AGREEMENT_ID`);
COMMIT;

-- `ENF_REVIEW`

CREATE TABLE IF NOT EXISTS `ENF_REVIEW` (
  `REVIEW_ID` int(11) NOT NULL AUTO_INCREMENT,
  `RECORD_ID` int(11) NOT NULL,
  `RECORD_TYPE_ID` int(11) NOT NULL,
  `REVIEW_TYPE_ID` int(11) NOT NULL,
  `COMMENT` varchar(4000) DEFAULT NULL,
  `IS_APPROVED` tinyint(1) DEFAULT NULL,
  `REVIEWER` varchar(255) DEFAULT NULL,
  `REVIEW_DATETIME` datetime DEFAULT NULL,
  PRIMARY KEY (`REVIEW_ID`),
  KEY `FK_reviewRecordTypeId` (`RECORD_TYPE_ID`),
  KEY `FK_reviewReviewTypeId` (`REVIEW_TYPE_ID`)
)

ALTER TABLE `ENF_REVIEW`
  ADD CONSTRAINT `FK_reviewRecordTypeId` FOREIGN KEY (`RECORD_TYPE_ID`) REFERENCES `ENF_R_DATA` (`ID`),
  ADD CONSTRAINT `FK_reviewReviewTypeId` FOREIGN KEY (`REVIEW_TYPE_ID`) REFERENCES `ENF_R_DATA` (`ID`);
COMMIT;

-- `ENF_L_REASON_DETAIL`

CREATE TABLE IF NOT EXISTS `ENF_L_REASON_DETAIL` (
  `LINK_ID` int(11) NOT NULL AUTO_INCREMENT,
  `REASON_ID` int(11) NOT NULL,
  `TYPE_ID` int(11) NOT NULL,
  `DETAIL` varchar(4000) NOT NULL,
  `CREATED_BY` varchar(255) NOT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL,
  PRIMARY KEY (`LINK_ID`),
  KEY `FK_enfLReasonDetailReasonIdenfReasonReasonId` (`REASON_ID`),
  KEY `FK_enfLReasonDetailTypeIdenfRefDataId` (`TYPE_ID`)
)

ALTER TABLE `ENF_L_REASON_DETAIL`
  ADD CONSTRAINT `FK_enfLReasonDetailReasonIdenfReasonReasonId` FOREIGN KEY (`REASON_ID`) REFERENCES `ENF_REASON` (`REASON_ID`),
  ADD CONSTRAINT `FK_enfLReasonDetailTypeIdenfRefDataTypeId` FOREIGN KEY (`TYPE_ID`) REFERENCES `ENF_R_DATA` (`ID`);
COMMIT;

-- `ENF_L_EA_ITEM_REPO_TYPE`

CREATE TABLE IF NOT EXISTS `ENF_L_EA_ITEM_REPO_TYPE` (
  `LINK_ID` int(11) NOT NULL AUTO_INCREMENT,
  `EA_ITEM_REPOSITORY_ID` int(11) NOT NULL,
  `TYPE_ID` int(11) NOT NULL,
  `CREATED_BY` varchar(255) NOT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL,
  PRIMARY KEY (`LINK_ID`),
  KEY `FK_enfLEAItemRepoLinkEAItemRepoId` (`EA_ITEM_REPOSITORY_ID`),
  KEY `FK_enfLEAItemRepoLinkTypeId` (`TYPE_ID`)
)

ALTER TABLE `ENF_L_EA_ITEM_REPO_TYPE`
  ADD CONSTRAINT `FK_enfLEAItemRepoLinkEAItemRepoId` FOREIGN KEY (`EA_ITEM_REPOSITORY_ID`) REFERENCES `ENF_EA_ITEM_REPOSITORY` (`EA_ITEM_REPOSITORY_ID`),
  ADD CONSTRAINT `FK_enfLEAItemRepoLinkTypeId` FOREIGN KEY (`TYPE_ID`) REFERENCES `ENF_R_DATA` (`ID`);
COMMIT;

-- `ENF_L_EA_ITEM_REPO_REASON`

CREATE TABLE IF NOT EXISTS `ENF_L_EA_ITEM_REPO_REASON` (
  `LINK_ID` int(11) NOT NULL AUTO_INCREMENT,
  `EA_ITEM_REPOSITORY_ID` int(11) NOT NULL,
  `REASON_ID` int(11) NOT NULL,
  `CREATED_BY` varchar(255) NOT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL,
  PRIMARY KEY (`LINK_ID`),
  KEY `FK_enfLEAItemRepoReasonLinkEAItemRepoId` (`EA_ITEM_REPOSITORY_ID`),
  KEY `FK_enfLEAItemRepoReasonLinkReasonId` (`REASON_ID`)
)

ALTER TABLE `ENF_L_EA_ITEM_REPO_REASON`
  ADD CONSTRAINT `FK_enfLEAItemRepoReasonLinkEAItemRepoId` FOREIGN KEY (`EA_ITEM_REPOSITORY_ID`) REFERENCES `ENF_EA_ITEM_REPOSITORY` (`EA_ITEM_REPOSITORY_ID`),
  ADD CONSTRAINT `FK_enfLEAItemRepoReasonLinkReasonId` FOREIGN KEY (`REASON_ID`) REFERENCES `ENF_REASON` (`REASON_ID`);
COMMIT;

-- `ENF_INTERACTION_DOCUMENT`

CREATE TABLE IF NOT EXISTS `ENF_INTERACTION_DOCUMENT` (
  `INTERACTION_DOCUMENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `INTERACTION_ID` int(11) NOT NULL,
  `DOCUMENT_ID` int(11) NOT NULL,
  `CREATED_BY` varchar(255) NOT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `LAST_MODIFIED_BY` varchar(255) DEFAULT NULL,
  `LAST_MODIFIED_DATETIME` datetime DEFAULT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL,
  PRIMARY KEY (`INTERACTION_DOCUMENT_ID`),
  KEY `FK_ENF_INTERACTION_DOCUMENT_INTERACTION_ID` (`INTERACTION_ID`)
)

ALTER TABLE `ENF_INTERACTION_DOCUMENT`
  ADD CONSTRAINT `FK_ENF_INTERACTION_DOCUMENT_INTERACTION_ID` FOREIGN KEY (`INTERACTION_ID`) REFERENCES `ENF_INTERACTION` (`INTERACTION_ID`);
COMMIT;

-- `ENF_EVIDENCE_DOCUMENT`

CREATE TABLE IF NOT EXISTS `ENF_EVIDENCE_DOCUMENT` (
  `EVIDENCE_DOCUMENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `DOCUMENT_ID` int(11) NOT NULL,
  `EVIDENCE_ID` int(11) NOT NULL,
  `CREATED_BY` varchar(255) NOT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `LAST_MODIFIED_BY` varchar(255) NOT NULL,
  `LAST_MODIFIED_DATETIME` datetime NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL,
  PRIMARY KEY (`EVIDENCE_DOCUMENT_ID`),
  KEY `FK_enfEvidenceDocumentEvidenceId` (`EVIDENCE_ID`)
)

ALTER TABLE `ENF_EVIDENCE_DOCUMENT`
  ADD CONSTRAINT `FK_enfEvidenceDocumentEvidenceId` FOREIGN KEY (`EVIDENCE_ID`) REFERENCES `ENF_EVIDENCE` (`EVIDENCE_ID`);
COMMIT;

-- `ENF_EA_ITEM_RESPONSE_DOCUMENT`

CREATE TABLE IF NOT EXISTS `ENF_EA_ITEM_RESPONSE_DOCUMENT` (
  `EA_ITEM_RESPONSE_DOCUMENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `DOCUMENT_ID` int(11) NOT NULL,
  `EA_ITEM_RESPONSE_ID` int(11) NOT NULL,
  `CREATED_BY` varchar(255) NOT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `LAST_MODIFIED_BY` varchar(255) NOT NULL,
  `LAST_MODIFIED_DATETIME` datetime NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL,
  PRIMARY KEY (`EA_ITEM_RESPONSE_DOCUMENT_ID`),
  KEY `FK_enfEAItemResponseDocumentEAItemResponseId` (`EA_ITEM_RESPONSE_ID`)
)

ALTER TABLE `ENF_EA_ITEM_RESPONSE_DOCUMENT`
  ADD CONSTRAINT `FK_enfEAItemResponseDocumentEAItemResponseId` FOREIGN KEY (`EA_ITEM_RESPONSE_ID`) REFERENCES `ENF_EA_ITEM_RESPONSE` (`EA_ITEM_RESPONSE_ID`);
COMMIT;

-- `ENF_EA_ITEM_RESPONSE`

CREATE TABLE IF NOT EXISTS `ENF_EA_ITEM_RESPONSE` (
  `EA_ITEM_RESPONSE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ENFORCEMENT_ACTION_ITEM_ID` int(11) NOT NULL,
  `RESPONSE_TYPE_ID` int(11) NOT NULL,
  `RESPONSE` varchar(4000) DEFAULT NULL,
  `IS_SENT` tinyint(1) NOT NULL DEFAULT 0,
  `COMMENT` varchar(4000) DEFAULT NULL,
  `CREATED_BY` varchar(255) NOT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `LAST_MODIFIED_BY` varchar(255) NOT NULL,
  `LAST_MODIFIED_DATETIME` datetime NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL,
  PRIMARY KEY (`EA_ITEM_RESPONSE_ID`),
  KEY `FK_enfEAItemResponseTypeId` (`RESPONSE_TYPE_ID`)
)

ALTER TABLE `ENF_EA_ITEM_RESPONSE`
  ADD CONSTRAINT `FK_enfEAItemResponseEAItemId` FOREIGN KEY (`EA_ITEM_RESPONSE_ID`) REFERENCES `ENF_ENFORCEMENT_ACTION_ITEM` (`ENFORCEMENT_ACTION_ITEM_ID`),
  ADD CONSTRAINT `FK_enfEAItemResponseTypeId` FOREIGN KEY (`RESPONSE_TYPE_ID`) REFERENCES `ENF_R_DATA` (`ID`);
COMMIT;

-- `ENF_EA_ITEM_REPOSITORY_DOCUMENT`

CREATE TABLE IF NOT EXISTS `ENF_EA_ITEM_REPOSITORY_DOCUMENT` (
  `EA_ITEM_REPOSITORY_DOCUMENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `DOCUMENT_ID` int(11) NOT NULL,
  `EA_ITEM_REPOSITORY_ID` int(11) NOT NULL,
  `CREATED_BY` varchar(255) NOT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `LAST_MODIFIED_BY` varchar(255) NOT NULL,
  `LAST_MODIFIED_DATETIME` datetime NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL,
  PRIMARY KEY (`EA_ITEM_REPOSITORY_DOCUMENT_ID`),
  KEY `FK_enfEAItemRepoDocumentEAItemRepoId` (`EA_ITEM_REPOSITORY_ID`)
)

ALTER TABLE `ENF_EA_ITEM_REPOSITORY_DOCUMENT`
  ADD CONSTRAINT `FK_enfEAItemRepoDocumentEAItemRepoId` FOREIGN KEY (`EA_ITEM_REPOSITORY_ID`) REFERENCES `ENF_EA_ITEM_REPOSITORY` (`EA_ITEM_REPOSITORY_ID`);
COMMIT;

-- `ENF_EA_ITEM_DOCUMENT`

CREATE TABLE IF NOT EXISTS `ENF_EA_ITEM_DOCUMENT` (
  `EA_ITEM_DOCUMENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `DOCUMENT_ID` int(11) NOT NULL,
  `ENFORCEMENT_ACTION_ITEM_ID` int(11) NOT NULL,
  `CREATED_BY` varchar(255) NOT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `LAST_MODIFIED_BY` varchar(255) NOT NULL,
  `LAST_MODIFIED_DATETIME` datetime NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL,
  PRIMARY KEY (`EA_ITEM_DOCUMENT_ID`),
  KEY `FK_enfEAItemDocumentEAItemId` (`ENFORCEMENT_ACTION_ITEM_ID`)
)

ALTER TABLE `ENF_EA_ITEM_DOCUMENT`
  ADD CONSTRAINT `FK_enfEAItemDocumentEAItemId` FOREIGN KEY (`ENFORCEMENT_ACTION_ITEM_ID`) REFERENCES `ENF_ENFORCEMENT_ACTION_ITEM` (`ENFORCEMENT_ACTION_ITEM_ID`);
COMMIT;

-- `ENF_AUDIT_HISTORY`

CREATE TABLE IF NOT EXISTS `ENF_AUDIT_HISTORY` (
  `AUDIT_HISTORY_ID` int(11) NOT NULL AUTO_INCREMENT,
  `RECORD_ID` int(11) NOT NULL,
  `RECORD_TYPE_ID` int(11) NOT NULL,
  `DESCRIPTION` varchar(255) NOT NULL,
  `ACTION_BY` varchar(255) NOT NULL,
  `EVENT_DATETIME` datetime NOT NULL,
  PRIMARY KEY (`AUDIT_HISTORY_ID`),
  KEY `FK_auditHistoryRecordTypeId` (`RECORD_TYPE_ID`)
)

ALTER TABLE `ENF_AUDIT_HISTORY`
  ADD CONSTRAINT `FK_auditHistoryTypeId` FOREIGN KEY (`RECORD_TYPE_ID`) REFERENCES `ENF_R_DATA` (`ID`);
COMMIT;